AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Proton Demo VPC Environment

Parameters:
 EnvName:
 Type: String
 Description: "Environment name"
 VpcCidr:
 Type: String
 Description: "CIDR block for VPC"
 Default: "10.0.0.0/16"

Resources:
 DemoVpc:
 Type: AWS::EC2::VPC
 Properties:
 CidrBlock: !Ref VpcCidr
 Tags:
 - Key: Name
 Value: !Ref EnvName

Outputs:
 VpcId:
 Description: "VPC ID"
 Value: !Ref DemoVpc